In [1]:
import numpy as np


In [3]:
array=np.array([23,45,54,55])
result=np.mean(array)
print(result)

44.25


In [12]:
value=np.array([2,3,45,5])
zero=np.zeros((3,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
fulll_method=np.full((3,4),10)
print(fulll_method)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [19]:
arange_method=np.arange(1,10,2)
arange_method

array([1, 3, 5, 7, 9])

In [22]:
identity_metrix=np.eye(3)
identity_metrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
random_value=np.random.rand(3,3)
print(random_value.dtype)


float64


In [19]:
arr_list=np.array([12.5 ,33.6,44.4,23.7,56.6])
convert_type=arr_list.astype(int)
print(convert_type.dtype)
print(convert_type)


int64
[12 33 44 23 56]


In [25]:
array=np.array([34,54,65,78,45,11,22])
print(np.sum(array))
print(np.min(array))
print(np.max(array))
print(round(np.mean(array),2))
print(np.std(array))
print(np.var(array))


309
11
78
44.14
21.944270787797056
481.55102040816325


In [ ]:
#indexing and slicing

In [33]:
array=np.array([34,76,56,45,90])

array([1:4])

SyntaxError: invalid syntax (1019329807.py, line 3)