In [1]:
import numpy as np


In [3]:
array=np.array([23,45,54,55])
result=np.mean(array)
print(result)

44.25


In [12]:
value=np.array([2,3,45,5])
zero=np.zeros((3,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
fulll_method=np.full((3,4),10)
print(fulll_method)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [19]:
arange_method=np.arange(1,10,2)
arange_method

array([1, 3, 5, 7, 9])

In [22]:
identity_metrix=np.eye(3)
identity_metrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])